### ISSUE TITLE
Feature request: Add support for JPEG-LS mapping tables

### ISSUE THREAD

**Issue by malaterre** [team-charls/charls#145]
It would nice to have JPEG-LS mapping tables in the long term. I have no idea on how complex implementation for reading/writing is. Could you comment @vbaderks ?

**Comment by vbaderks** [comment]
Support for JPEG-LS mapping tables in on the roadmap for 2.4.0 (first 2.3.0 needs to be released).

The tables specs are very flexible. Tables can be added at several different locations in the bit stream and there are a couple of corner cases. Both encoding and decoding needs to be place, otherwise the feature cannot be used.

As this feature is also requested by https://github.com/team-charls/charls/issues/90, closing this one as duplicate.
