### ISSUE TITLE
Too much compressed data

### ISSUE THREAD

**Issue by malaterre** [team-charls/charls#16]
I can reproduce a failure to decompress using CharLS 1.1 (issue is present in CharLS 1.0), this is originally a bug tracked in [Debian](https://bugs.debian.org/824818). With the reference jls, I can get `JpegLsDecodeStream` to return `TooMuchCompressedData`:

```
(gdb) 
297		ByteStreamInfo outputInfo = FromByteArray(outputBuffer.data(), outputBuffer.size());
(gdb) 
298		err = JpegLsDecodeStream(outputInfo, compressedByteStream, &info);
(gdb) 
299		if (err != OK)
(gdb) p err
$1 = TooMuchCompressedData
```

**Comment by malaterre** [comment]
The dataset are available as DICOM files using either:
* http://gdcm.sourceforge.net/thingies/JPEG_LS_InvalidEscapeSequence_COM_padding.dcm

or
* http://gdcm.sourceforge.net/thingies/JPEG_LS_InvalidEscapeSequence.dcm

**Comment by malaterre** [comment]
The good news is that CharLS git/master does work. So the issue only affect release 1.0 and 1.1.

**Comment by vbaderks** [comment]
Hi,

This JPEG-LS image has been compressed with DicomObjects: 6.35.0.67. This can be seen as the JPEG-LS stream has a JPEG comment marker segment (xFFFE) with the text: "Compressed by DicomObjects: 6.35.0.67".

CharLS detects that when all pixels are decoded, there are still 2 bits not decoded and will report this as a failure. This problem can be caused by a failure in the encoding process (DicomObjects library) or the decoding process (CharLS).

Do you have access to the original uncompressed image?

Note: the original loco binaries cannot handle JPEG comment markers, so I am currently not able to use another tool to decode the image.

**Comment by malaterre** [comment]
@vbaderks If you check my earliest post you'll find a link to a stripped down version:

* http://gdcm.sourceforge.net/thingies/JPEG_LS_InvalidEscapeSequence.dcm

It does not contains a COM marker, so it may be simplier for you.

**Comment by malaterre** [comment]
This appear to be a bug in the JPEG-LS stream itself. CharLS does properly report the error as 'TooMuchCompressedData', so there is not much one can do. This is up to the application decoding the stream to decide whether or not to accept an error of type 'TooMuchCompressedData'. For reference the corrected stream is at:

* http://gdcm.sourceforge.net/thingies/JPEG_LS_InvalidEscapeSequence_Correct.dcm
