### ISSUE TITLE
API to handle application data markers

### ISSUE THREAD

**Issue by malaterre** [team-charls/charls#180]
This is a feature request to handle output from another famous open-source JPEG-LS encoder (1). Basically to losslessly-encode in RGB space, one need to (sample interleave mode is used here):

`% jpeg -ls 2 -c rgb.ppm rgb.jls
`

In which case output contains an Adobe marker 14:

`Offset 0x0002 Marker 0xffee APPE Reserved for Application Use length variable 0x0e`

It turns out charls (git/master as of today) decoding simply discard any application data marker segments:

```
    case jpeg_marker_code::application_data0:
    case jpeg_marker_code::application_data1:
    case jpeg_marker_code::application_data2:
    case jpeg_marker_code::application_data3:
    case jpeg_marker_code::application_data4:
    case jpeg_marker_code::application_data5:
    case jpeg_marker_code::application_data6:
    case jpeg_marker_code::application_data7:
    case jpeg_marker_code::application_data9:
    case jpeg_marker_code::application_data10:
    case jpeg_marker_code::application_data11:
    case jpeg_marker_code::application_data12:
    case jpeg_marker_code::application_data13:
    case jpeg_marker_code::application_data14:
    case jpeg_marker_code::application_data15:
        read_application_data_segment(); // <-- skip
        break;
```

Assuming that Adobe marker 14 is valid for JPEG-LS, I would like to request a framework identical to the one introduced for comment marker (COM), where the API allow application programer to specify a custom callback. Here the value of the application data marker will be passed along the marker value. For example:

`typedef void(CHARLS_API_CALLING_CONVENTION* charls_at_application_data_maker_handler)(uint8_t application_data_marker /* range 0-15*/, const void* data, size_t size, void* user_context);
`

(1) https://github.com/thorfdbg/libjpeg/

**Comment by vbaderks** [comment]
Hi @malaterre,

Request is fine. I will add the proposed callback mechanism to make it possible for applications to be notified of application markers present in the JPEG-LS bit stream.
I will also add an API to write application markers during encoding to make it easier to verify the round trip.

Note:  the "official" JPEG-LS way, as documented in ISO/IEC 14495-1, is to use a SPIFF header (APP8 marker) to store color space information in a JPEG-LS stream. SPIFF headers are however rarely supported. The SPIFF standard also only supports "uncalibrated" RGB as the RGB color space option. Most web friendly RGB images are sRGB.

**Comment by malaterre** [comment]
@vbaderks Long story short, there seems to be a disagreement here. See the "long" answer from @thorfdbg:

https://github.com/thorfdbg/libjpeg/pull/66#issuecomment-1059397147

I was also under the impression that a SPIFF header with RGB color space would be enough. If I understand the comment above correctly, the bitstream itself (JPEG-LS bitstream, not the format) *must* contains an Adobe RGB marker (application marker 14), otherwise a color space of YUV is implied. So both the format (SPIFF with RGB marker) and JPEG-LS bistream with Adobe marker RGB is required for example.

I have not read JPEG-XT standard so far, so this solely based on Thomas' comment.

**Comment by thorfdbg** [comment]
Am 06.03.22 um 15:17 schrieb Mathieu Malaterre:
> @vbaderks <https://github.com/vbaderks> Long story short, there seems to
> be a disagreement here. See the "long" answer from @thorfdbg
> <https://github.com/thorfdbg>:
> 
> thorfdbg/libjpeg#66 (comment)
> <https://github.com/thorfdbg/libjpeg/pull/66#issuecomment-1059397147>
> 
> I was also under the impression that a SPIFF header with RGB color space
> would be enough. If I understand the comment above correctly, the
> bitstream itself (JPEG-LS bitstream, not the format) /must/ contains an
> Adobe RGB marker (application marker 14), otherwise a color space of YUV
> is implied. So both the format (SPIFF with RGB marker) and JPEG-LS
> bistream with Adobe marker RGB is required for example.

Well, that's not quite the correct statement; it is more a side effect
and a property of the software rather than a formal requirement that
follows from anything specified in JPEG LS. As said before, JPEG-LS does
not define a colorspace, so it does not tell you which meaning the
samples have it reconstructs.

That the software currently assigns to them the meaning of "YUV" is more
a side-effect of applying the same logic to JPEG-LS as it does for JPEG.
For JPEG, this logic has been formalized in in 18477-1 (JPEG XT), and
this is what the software is a reference implementation of. For JPEG-LS,
the "RGB marker" was never formalized, but it can be embedded without
problems because the LS codestream was constructed as a blue-print of
the JPEG codestream. For LS, you would need a file format to specify a
color space.

This is all not very ideal, indeed. The *real* solution would be to make
this code part of a larger library that handles color spaces correctly,
but this is where the JPEG standard and the JPEG-LS standard end, and
thus where the purpose of this software ends.

Greetings,
	Thomas

**Comment by vbaderks** [comment]
Support to read and write APPn markers have been added with commit 8225d1627d19a64e080818bf729254219024584d
