### ISSUE TITLE
16 bpc error

### ISSUE THREAD

**Issue by fnordware** [team-charls/charls#24]
I'm getting an error when reading (or maybe writing) 16-bit JPEG-LS files. I'm using the 1.x-master branch if that makes a difference. I'm attaching a sample program that shows what I'm doing.

[CharLS_bitdepth_test.cpp.zip](https://github.com/team-charls/charls/files/621064/CharLS_bitdepth_test.cpp.zip)

**Comment by vbaderks** [comment]
Hi,

I did a quick test. During the 10 bit test I get an assert in the code:

inlinehint LONG ModRange(LONG Errval) const
	{
		ASSERT(std::abs(Errval) <= RANGE);
It seems that the input pixels are outside the defined range. I added the following lines to your program, after the loop were the originalImageBuf is filled:

    // Verify input pixels.
    PIXTYPE* buffer = reinterpret_cast<PIXTYPE*>(originalImageBuf);
    for (int i = 0; i < imageBufferSize / 2; i++)
    {
        if (buffer[i] > maxVal)
        {
            std::cout << "bad value" << std::endl;
        }
    }
On my system "bad value" is printed. You may want to check your input routine.

Note: the InterleaveMode::Sample option describes better how your pixels are defined in memory: RGBRGBRGB.

**Comment by fnordware** [comment]
Hmmm, maybe your compiler does the float to ushort conversion differently? Here's another version that should make it more explicit.

[CharLS_bitdepth_test2.cpp.zip](https://github.com/team-charls/charls/files/623310/CharLS_bitdepth_test2.cpp.zip)

**Comment by fnordware** [comment]
Actually, your ILV_SAMPLE suggestion fixed my problem (not included in the above source file). The other bit depths seemed to assume it with ILV_NONE, but 16-bit needed it set, apparently.

**Comment by vbaderks** [comment]
Hi,

I did some more analyzing of the problem and the ILV_SAMPLE is a solution, but not a complete one.

The first problem is that your test application doesn't initialize the input buffer correctly:
RGBPixel<PIXTYPE> &pix = originalImageBuf[(y * imageHeight) + x];
should be:
RGBPixel<PIXTYPE> &pix = originalImageBuf[(y * imageWidth) + x];

note: same problem also in the compare pixel routine

On my environment, malloc will return in debug builds a buffer filled with 0xCD values.  As not the complete buffer was initialized some 0xCD values were still present and 0xCDCD is larger then 1024 (max allowed valid value for 10 bit encoding). This caused the assert.
After fixing your test application, all the tests also passed with ILV_SAMPLE but not with ILV_NONE for 16 bit data . ILV_NONE should however also work. I tracked this problem down and it is a bug in CharLS, I created #25 to track this bug.

To prevent that CharLS creates bad encoded pixels when the values in the buffer are out of range I created #26

**Comment by fnordware** [comment]
Whoops, sorry about the sloppiness. Yeah, I guess GCC was initializing to 0x00 so I didn't get that problem. Glad something came out of it though.

Here's a fixed file for posterity, BTW: [CharLS_bitdepth_test3.cpp.zip](https://github.com/team-charls/charls/files/626097/CharLS_bitdepth_test3.cpp.zip)


Does the interleave only describe the buffer, or also something in how the file is written?

**Comment by vbaderks** [comment]
The interleave option in charls describes both the format of the input and control the generated encoded bit stream. This to keep the implementation simple and fast.
With ILV_SAMPLE the bit stream will contain 1 multi-component scan (buffer with RGBRGB..) and with ILV_NONE the bit stream will contain 3 single-component scans, (3 buffers with RR.., GGG, BBB), assuming we are encoding color image.
Using multiple components provides more freedom, components don't have to be of same dimensions and the JPEG-LS algorithm has the potential option to compress better. 

All decoders are required to support all 3 ILV options. As most computer systems can only render color images in the ILV_SAMPLE format, it is typical format. But it is not to difficult for an app to convert from one format to the other.

Note: the actual info which color space is used is not stored in a JPEG-LS bit stream (by design). In the medical domain (DICOM) the JPEG-LS stream is embedded in another file, which stores that information.
More info can be found in the ITU-T T.87 document which documents the JPEG-LS standard (free downlink can be found at jpeg.org).
