### ISSUE TITLE
how to encode and decode an 20bitsdeep bmp?

### ISSUE THREAD

**Issue by duzhizeng** [team-charls/charls#284]

**Comment by vbaderks** [comment]
CharLS includes a sample application that shows how to encode a 3 * 8 bits (24 bits) color .bmp file to JPEG-LS.
Not sure what a 20 bits deep bmp is? Grayscale or Color?

**Comment by duzhizeng** [comment]
> CharLS includes a sample application that shows how to encode a 3 * 8 bits (24 bits) color .bmp file to JPEG-LS. Not sure what a 20 bits deep bmp is? Grayscale or Color?

the image format is RAW-RGGB,each pixel has 12or 16 or 20bits

**Comment by vbaderks** [comment]
I am not familiar with the RAW-RGGB format.  It seem to be a direct image of a sensor with a color filters in a typical pattern (source https://en.wikipedia.org/wiki/Bayer_filter), with a typical arrangement of:

G R G R G R....
B G B G B G
G R G R G R
B G B G B G

To encode this image the following steps could be used:
- extract the 3 colors and put them in 3 buffers.
- encode each of these buffers as a JPEG-LS scan

The problem is that there are more green pixels (in the height) then red or blue. Red and blue can be considered sub-sampled in this context. The JPEG-LS standard supports sup-sampling. This is however a feature that is not implemented by the current implementation of CharLS.

An alternative would to encode the whole image as grayscale, this would however give a bad compression ratio.
