### ISSUE TITLE
Do not force std=c++14

### ISSUE THREAD

**Issue by malaterre** [team-charls/charls#46]
Right now c++14 is being used for both implementation detail and API in CharLS. It would be nice to make it optional so as to compile with newer/older standard for advanced users. See patch in Debian:

* https://salsa.debian.org/med-team/charls/blob/master/debian/patches/noexplicitstd.patch

**Comment by vbaderks** [comment]
Hi,

Since commit c391025c824cebe17d0d8bbda57a23b6661496fa the CMake script for CharLS has been updated to "modern" CMake v3.9

The old settings of CMAKE_CXX_FLAGS is no longer used. It has been replaced with:

set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

This setting only defines the minimum required C++ version, CMake should by itself select the correct C++ version based on global settings, dependencies and global settings, see also:
https://crascit.com/2015/03/28/enabling-cxx11-in-cmake/

Would this solution work for your need?

What is the minimum version of CMake supported by Debian?

**Comment by vbaderks** [comment]
Hi @malaterre,

I assume that the provided solution works for your case, if not please let me know.
