### ISSUE TITLE
[question/enhancement] Python and PIL support

### ISSUE THREAD

**Issue by planetmarshall** [team-charls/charls#85]
I've created a plugin using CharLS to add JPEG-LS support to the Python [Pillow](https://pillow.readthedocs.io/en/stable/) library. It's available here - https://github.com/planetmarshall/pillow-jpls and via pip at https://pypi.org/project/pillow-jpls/1.0.0/

The python bindings use pybind, and could be worth incorporating into CharLS in their own right - this is something I'd be happy to create a PR for if it'd be useful, though you'd probably want to decide what method you want to use for including external dependencies. Currently I use [conan](https://conan.io/).

One thing I was a bit unclear about from the spec is what to do with multi component images that are non interleaved (conformance tests 1 and 4). Since Pillow images are always interleaved, I de-interleave them in the Python binding and convert to planar, which satisfies the conformance tests.

**Comment by vbaderks** [comment]
Hi Andrew,

Thanks for the offer, but I prefer at the moment not to add external dependencies. 

Conformance test 1\4
If you are decoding then it is important to be able to handle all interleave modes. It makes sense to convert them to interleaved if that is the format Pillow uses.
If you are encoding, you are free to select any of the 3 options. If the image is already interleaved, then it is easy to also encode them interleaved. For some types of images however, encoding by plane may result in a smaller image.

Questions:
1) Is there a special reason to use PyBind instead of ctypes? 

2) Is it ok if I add a link to you repo in the readme.md, so that other people may find your Python plugin?

**Comment by planetmarshall** [comment]
Hi Victor, thanks for the response.

> 
> Questions:
> 
> 1. Is there a special reason to use PyBind instead of ctypes?

A couple of reasons. We were already using pybind for an internal project that spawned the plugin. It also simplifies a few things that can be awkward with ctypes such as loading the various platform specific varieties of dynamic libraries.

> 2. Is it ok if I add a link to you repo in the readme.md, so that other people may find your Python plugin?

Sure, no problem.

**Comment by vbaderks** [comment]
Commit e4e6fd35ca7022fb5e761e499b05473e22f3ddda adds a link.
